package org.kemricdc.entities;
// Generated Nov 28, 2014 11:52:32 AM by Hibernate Tools 3.6.0

import org.kemricdc.constants.IdentifierType;

/**
 * PersonIdentifier generated by hbm2java
 */
public class PersonIdentifier implements java.io.Serializable {

    private IdentifierType identifierType;
    private String identifier;

    public PersonIdentifier() {
    }

    public PersonIdentifier(IdentifierType identifierType) {
        this.identifierType = identifierType;

    }

    public PersonIdentifier(IdentifierType identifierType, String identifier) {
        this.identifierType = identifierType;
        this.identifier = identifier;
    }

    public IdentifierType getIdentifierType() {
        return this.identifierType;
    }

    public void setIdentifierType(IdentifierType identifierType) {
        this.identifierType = identifierType;
    }

    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

}
